const getTypeName = name => "@@aspectSelectionForm/" + name;

export default {
	CHANNEL_SELECT_ACTION: getTypeName("CHANNEL_SELECT_ACTION"),
	CHANNEL_SELECT_SUCCESS: getTypeName("CHANNEL_SELECT_SUCCESS"),
	CATEGORY_SUCCESS: getTypeName("CATEGORY_SUCCESS"),
	CUSTOM_CATEGORY_SUCCESS: getTypeName("CUSTOM_CATEGORY_SUCCESS"),
	GET_ASPECTS_SUCCESS: getTypeName("GET_ASPECTS_SUCCESS"),
	SET_CATEGORY_LIST_VISIBLE: getTypeName("SET_CATEGORY_LIST_VISIBLE"),
	SET_ASPECT_LIST_VISIBLE: getTypeName("SET_ASPECT_LIST_VISIBLE")
};
