const getTypeName = name => "@@aspectSelectionForm/" + name;

export default {
	CHANNEL_SELECT_ACTION: getTypeName("CHANNEL_SELECT_ACTION"),
	CHANNEL_SELECT_LOADING: getTypeName("CHANNEL_SELECT_LOADING"),
	CHANNEL_SELECT_SUCCESS: getTypeName("CHANNEL_SELECT_SUCCESS"),
	CHANNEL_SELECT_ERROR: getTypeName("CHANNEL_SELECT_ERROR"),
	CATEGORY_LOADING: getTypeName("CATEGORY_LOADING"),
	CATEGORY_SUCCESS: getTypeName("CATEGORY_SUCCESS"),
	CUSTOM_CATEGORY_SUCCESS: getTypeName("CUSTOM_CATEGORY_SUCCESS"),
	CATEGORY_ERROR: getTypeName("CATEGORY_ERROR")
};
